name = "Server Information Panel Experimental"; 								// name 
picture = "ServerPanel/gui/imageset/logo-server-panel.edds";			// picture in expanded description
logoSmall = "ServerPanel/gui/imageset/logo-server-panel.edds";	// icon next to mod name when description is not expanded
logo = "ServerPanel/gui/imageset/logo-server-panel.edds";				// logo below game menu
logoOver = "ServerPanel/gui/imageset/logo-server-panel.edds";	// on mouse hover over logo
tooltip = "This mod allow server owner to display some informations about there server";							// tool tip on mouse hover
overview = "This mod allow server owner to display some informations about there server"; 						// overview
action = "https://www.mydayz.eu/";					// link
author = "LaGTeK";								// author
version = "1.0";								// version